// <auto-generated />
using System;
using CafeIES.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeIES.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312101315_AddInstituto")]
    partial class AddInstituto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeIES.Shared.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Emoji = "🥖",
                            Nombre = "Bocadillos",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Emoji = "🥗",
                            Nombre = "Ensaladas",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Emoji = "🥤",
                            Nombre = "Bebidas",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Emoji = "🍰",
                            Nombre = "Postres",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Emoji = "☕",
                            Nombre = "Café",
                            Orden = 5
                        });
                });

            modelBuilder.Entity("CafeIES.Shared.Models.FranjaHoraria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FranjasHorarias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Descripcion = "Antes de entrar",
                            HoraFin = "08:00",
                            HoraInicio = "07:30",
                            Turno = 0
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Descripcion = "Recreo",
                            HoraFin = "11:30",
                            HoraInicio = "11:00",
                            Turno = 0
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Descripcion = "Antes de entrar",
                            HoraFin = "14:00",
                            HoraInicio = "13:45",
                            Turno = 1
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Descripcion = "Recreo",
                            HoraFin = "17:30",
                            HoraInicio = "17:00",
                            Turno = 1
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Descripcion = "Antes de entrar",
                            HoraFin = "21:00",
                            HoraInicio = "20:45",
                            Turno = 2
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Descripcion = "Recreo",
                            HoraFin = "23:20",
                            HoraInicio = "23:00",
                            Turno = 2
                        });
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Instituto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoCorto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCorto")
                        .IsUnique();

                    b.ToTable("Institutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CodigoCorto = "IES-1",
                            Direccion = "",
                            Nombre = "IES Instituto 1"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CodigoCorto = "IES-2",
                            Direccion = "",
                            Nombre = "IES Instituto 2"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CodigoCorto = "IES-3",
                            Direccion = "",
                            Nombre = "IES Instituto 3"
                        });
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Invitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsosActuales")
                        .HasColumnType("int");

                    b.Property<int?>("UsosMaximos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Invitaciones");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.LineaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("LineasPedido");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NumeroPedido")
                        .HasColumnType("int");

                    b.Property<string>("ReferenciasPago")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "FechaCreacion");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstitutoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int?>("Turno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InstitutoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.LineaPedido", b =>
                {
                    b.HasOne("CafeIES.Shared.Models.Pedido", "Pedido")
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeIES.Shared.Models.Producto", "Producto")
                        .WithMany("Lineas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Pedido", b =>
                {
                    b.HasOne("CafeIES.Shared.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Producto", b =>
                {
                    b.HasOne("CafeIES.Shared.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Usuario", b =>
                {
                    b.HasOne("CafeIES.Shared.Models.Instituto", "Instituto")
                        .WithMany("Usuarios")
                        .HasForeignKey("InstitutoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Instituto");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Instituto", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Pedido", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Producto", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("CafeIES.Shared.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
